# syntax=docker/dockerfile:1

FROM golang:1.18.0-alpine3.15

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /docker-ws-gin

EXPOSE 8080

CMD [ "/docker-ws-gin" ]